_BASE_: "Base-TotalText-Polygon_debug.yaml"
MODEL:
  WEIGHTS: "weights/TESTR/totaltext_testr_R_50_polygon.pth"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (200000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/TESTR/totaltext/TESTR_R_50_Polygon"
DATASETS:
  TRAIN: ("totaltext_poly_train",)
  TEST: ("totaltext_poly_val",)
#  TRAIN: ("icdar2015_poly_train",)
#  TEST: ("icdar2015_poly_test", )
#  TEST: ("ctw1500_word_poly_test", )