_BASE_: "../Base-CLIP-BAText.yaml"
DATASETS:
  TRAIN: ("mltbezier_word_train", "totaltext_train", "syntext1_train", "syntext2_train", "icdar2013_train", "icdar2015_train") 
  TEST: ("icdar2015_test",)