_BASE_: "Base-Pretrain-ic15.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE: 
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
    NORM: "SyncBN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
    POOLER_RESOLUTION: (16, 64)
SOLVER:
  IMS_PER_BATCH: 8 
  BASE_LR: 0.01
  STEPS: (160000, 220000)
  MAX_ITER: 260000
  CHECKPOINT_PERIOD: 20000
TEST:
  EVAL_PERIOD: 20000
INPUT:
  IS_ROTATE: True
OUTPUT_DIR: "output/batext/pretrain/v2_ic15_attn_R_50"

