_BASE_: "Base-ReCTS.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE: 
    NAME: "build_fcos_resnet_bifpn_backbone"
  BiFPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    OUT_CHANNELS: 256
    NUM_REPEATS: 2
    NORM: "SyncBN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn"
    USE_COORDCONV: True
    USE_AET: True
    VOC_SIZE: 5462
    CUSTOM_DICT: "chn_cls_list"
SOLVER:
  IMS_PER_BATCH: 8 
  BASE_LR: 0.001
  STEPS: (140000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 10000
INPUT:
  CROP:
    ENABLED: False
OUTPUT_DIR: "output/batext/rects/v2_attn_R_50"

