_BASE_: "Base-CLIP-ic15.yaml"
MODEL:
  META_ARCHITECTURE: "CLIPOneStageRCNN"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn" 
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  MAX_ITER: 5500
  CHECKPOINT_PERIOD: 500
DATALOADER:
  NUM_WORKERS: 1
INPUT:
  MIN_SIZE_TRAIN: (980, 1044, 1108, 1172, 1236, 1300, 1364, 1428, 1492)
  MAX_SIZE_TRAIN: 2900
  MIN_SIZE_TEST: 2000
  MAX_SIZE_TEST: 4000
  IS_ROTATE: True
TEST:
  EVAL_PERIOD: 500
OUTPUT_DIR: "output/batext/ic15/v1_attn_R_50"
CLIP:
  score_concat_index: "p4"
  TEXT_ENCODER:
    transformer_layers: 3
  CONTEXT_DECODER:
    transformer_layers: 2
  VISUAL_PROMPT_GENERATOR:
    transformer_layers: 2


