_BASE_: "Base-CTW1500.yaml"
MODEL:
  WEIGHTS: "weights/TESTR/pretrain_testr_R_50.pth"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    NUM_FEATURE_LEVELS: 4
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.1
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
SOLVER:
  STEPS: (300000,)
  IMS_PER_BATCH: 8
  BASE_LR: 2e-5
  LR_BACKBONE: 2e-6
  WARMUP_ITERS: 0
  MAX_ITER: 200000
  CHECKPOINT_PERIOD: 10000
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/TESTR/ctw1500/TESTR_R_50"
